version: '3.8'
services:
  mcp-broker:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
    volumes:
      - .env:/app/.env:ro
    restart: unless-stopped 